# Generated by Django 4.2.13 on 2024-08-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('progress', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
