# Generated by Django 4.2.13 on 2024-09-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_processingprogress_delete_fileprocess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessingProgress',
            new_name='ProcessedFile',
        ),
    ]
