# Generated by Django 4.2.13 on 2024-09-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_rename_processingprogress_processedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcf_file_name', models.CharField(max_length=255)),
            ],
        ),
    ]
